version: '3.7'
networks:
  test:
    name: fabric_test
services:
  ca_org2:
    image: hyperledger/fabric-ca:1.5.15
    container_name: ca_org2
    environment:
    - FABRIC_CA_SERVER_CA_NAME=ca-org2
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=7054
    - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    - FABRIC_CA_SERVER_CA_BOOTSTRAP_ENTRIES=admin:adminpw
    ports:
    - 8054:7054
    - 18054:17054
    volumes:
    - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    networks:
    - test

  couchdb.peer0.org2.example.com:
    container_name: couchdb.peer0.org2.example.com
    image: couchdb:3.3.2
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=adminpw
    ports:
    - 6984:5984
    networks:
    - test

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:2.5.14
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org2.example.com
    - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:7052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org2.example.com:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    - CORE_PEER_CHAINCODE_EXTERNALBUILDERS=[{"name":"ccaas-builder","path":"/opt/hyperledger/builders/ccaas"}]
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
    - ../../builders/ccaas:/opt/hyperledger/builders/ccaas
    - peer0.org2.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
    - 8051:7051
    - 10443:9443
    depends_on:
    - couchdb.peer0.org2.example.com
    networks:
    - test

volumes:
  peer0.org2.example.com:
