- &id504
  Name: Org4MSP
  ID: Org4MSP
  MSPDir: organizations/peerOrganizations/org4.example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('Org4MSP.admin', 'Org4MSP.peer', 'Org4MSP.client')
    Writers:
      Type: Signature
      Rule: OR('Org4MSP.admin', 'Org4MSP.client')
    Admins:
      Type: Signature
      Rule: OR('Org4MSP.admin')
    Endorsement:
      Type: Signature
      Rule: OR('Org4MSP.peer')
  AnchorPeers:
  - Host: peer0.org4.example.com
    Port: 7051
